### ISSUE TITLE
successfully installed unknown-0.0.0

### ISSUE THREAD

**Issue by lbtbs** [marph91/joplin-sticky-notes#3]
Hi, I followed the installation instructions and this happened:

...@pop-os:~$ pip install git+https://github.com/marph91/joplin-sticky-notes.git
Command 'pip' not found, but can be installed with:
sudo apt install python3-pip
...@pop-os:~$ sudo apt install python3-pip
...@pop-os:~$ pip install git+https://github.com/marph91/joplin-sticky-notes.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/marph91/joplin-sticky-notes.git
  Cloning https://github.com/marph91/joplin-sticky-notes.git to /tmp/pip-req-build-w4n_85po
  Running command git clone --filter=blob:none --quiet https://github.com/marph91/joplin-sticky-notes.git /tmp/pip-req-build-w4n_85po
  Resolved https://github.com/marph91/joplin-sticky-notes.git to commit faa7e9912c6411afc60d970df9eb32dbc5906fb4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=961 sha256=4b34b9b6973c05a23b906ad485854a441269048f9dec625e49dd76807295348c
  Stored in directory: /tmp/pip-ephem-wheel-cache-pa0cdzy6/wheels/7f/60/43/6c2f34e3a73f733374d7421d6371370ae78c99cc786f42488d
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0

My trying to use joplin-sticky-notes was unsuccessful of course:

...@pop-os:~$ python -m joplin_sticky_notes
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3

What should I do now?

**Comment by marph91** [comment]
Hi, in general console output and code is better readable when inside triple backticks (```).

The output looks wrong. The package should be called `joplin-sticky-notes`. Your command looks correct, though. Here is an example output of a working installation:

```
$ pip install git+https://github.com/marph91/joplin-sticky-notes.git
...
Building wheels for collected packages: joplin-sticky-notes
  Building wheel for joplin-sticky-notes (pyproject.toml) ... done
  Created wheel for joplin-sticky-notes: filename=joplin_sticky_notes-0.0.1-py3-none-any.whl size=22626 sha256=83a519c90d470bd9e0264af0cfe91dc2876cb3dd4b1baf8cf1869d2fdd1c98d9
  Stored in directory: /tmp/pip-ephem-wheel-cache-yboupf9u/wheels/7f/60/43/6c2f34e3a73f733374d7421d6371370ae78c99cc786f42488d
Successfully built joplin-sticky-notes
Installing collected packages: joplin-sticky-notes
Successfully installed joplin-sticky-notes-0.0.1
```

---

```
$ python -m joplin_sticky_notes
Command 'python' not found, did you mean:
command 'python3' from deb python3
```

I guess the command should be `python3 -m joplin_sticky_notes` on your machine. There might be simply no alias to `python`. Maybe at the installation, you could try the command `pip3` instead of `pip`.

---

At the end, using the [prebuilt executable](https://github.com/marph91/joplin-sticky-notes/actions/runs/6714237036) might be more convenient in your case, if you don't mind the filesize of 66 MB.
