### ISSUE TITLE
Error "No icon set"

### ISSUE THREAD

**Issue by zimcad** [marph91/joplin-sticky-notes#7]
when i want to start the app via powershell in windows 10, there comes up the error:

QSystemTrayIcon::setVisible: No Icon set

python3.12
Joplin 3.0.12

any ideas?

**Comment by marph91** [comment]
I can reproduce this. Actually, the app is starting properly in the tray. Just the tray icon isn't displayed (it's a blank space).

![image](https://github.com/user-attachments/assets/2924a380-a114-4d82-97c3-03881f18990b)

~~I'm trying to find out why the icon isn't included properly.~~

**Edit**: The logo should display now, too. You need to execute `pip install git+https://github.com/marph91/joplin-sticky-notes.git` again. Uninstalling the module before might be necessary (`pip uninstall joplin_sticky_notes`).

**Comment by zimcad** [comment]
works perfect, thanks!
